---
- name: Create user on all servers
  hosts: all
  tasks:
    - name: user creation
      user:
        name: satya
        password: satya
        uid: 2323
        comment: "a normal user"
        shell: /bin/bash
        home: /tmp/satya

...
