---
- hosts: app
  become: yes
  tasks:
    - name: Copy Dynamic inventory
      copy:
        src: /home/ec2-user/myhosts.ini
        dest: /home/ec2-user/myhosts.txt

    - name: Creating Directory
      file:
        state: directory
        dest: /home/ec2-user/test

    - name: Copying
      copy:
        src: /home/ec2-user/myhosts.ini
        dest: /opt/serveewr.txt